(function(){
'use strict';const $=id=>document.getElementById(id),I=MaterialInventory;
const message=text=>{$('inventoryStatus').textContent=text;};
function load(){const m=I.get($('inventoryMaterial').value);$('inventoryUnit').value=m?.unit||'g';$('inventoryUnit').disabled=Boolean(m&&m.quantity>0);$('inventoryLow').value=String(m?.low??0);$('inventoryAmount').value='';$('inventoryNote').value='';$('inventoryAction').value=m?'in':'set';$('inventoryCurrent').textContent=m?`現在：${m.quantity} ${m.unit}`:'未登録です。まず現在の数量を登録してください。';}
function render(){const host=$('inventoryRows');host.replaceChildren();let registered=0,zero=0,low=0;for(const item of ClientStones.items){const m=I.get(item.id),row=document.createElement('tr');const values=[item.name,m?`${m.quantity} ${m.unit}`:'未登録',!m?'数量を登録':m.quantity===0?'在庫切れ':m.quantity<=m.low?'補充目安以下':'在庫あり'];if(m){registered++;if(m.quantity===0)zero++;else if(m.quantity<=m.low)low++;}for(const value of values){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}const td=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='数量を変更';button.setAttribute('aria-label',item.name+'の数量を変更');button.addEventListener('click',()=>{$('inventoryMaterial').value=item.id;load();$('inventoryAmount').focus();$('inventoryForm').scrollIntoView({block:'center',behavior:'smooth'});});td.append(button);row.append(td);host.append(row);}$('inventorySummary').textContent=`登録 ${registered}/25種類 ・ 在庫切れ ${zero} ・ 補充目安以下 ${low}`;
const log=$('inventoryHistory');log.replaceChildren();for(const h of I.snapshot().history.slice(-20).reverse()){const item=ClientStones.items.find(s=>s.id===h.id),li=document.createElement('li'),labels={set:'棚卸し',in:'入荷',out:'使用',settings:'設定'};li.textContent=`${new Date(h.at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}／${item.name}／${labels[h.action]}：${h.before??'未登録'} → ${h.after} ${h.unit}${h.note?'／'+h.note:''}`;log.append(li);}if(!log.children.length){const li=document.createElement('li');li.textContent='まだ記録がありません。';log.append(li);}}
for(const item of ClientStones.items){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;$('inventoryMaterial').append(o);}
$('inventoryMaterial').value=ClientStones.items[0].id;$('inventoryMaterial').addEventListener('change',load);
$('inventorySave').addEventListener('click',()=>{try{const item=ClientStones.items.find(s=>s.id===$('inventoryMaterial').value);I.change(item.id,$('inventoryAction').value,$('inventoryAmount').value,$('inventoryUnit').value,$('inventoryLow').value,$('inventoryNote').value);render();load();message(item.name+'の在庫をこのブラウザに保存しました。');document.dispatchEvent(new Event('inventorychange'));}catch(e){message(e.message);}});
$('inventoryExport').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(I.snapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='jico-inventory-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
let pending=null;$('inventoryImport').addEventListener('change',async e=>{pending=null;$('inventoryRestore').disabled=true;try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('在庫JSONは5MB以下にしてください。');pending=InventoryStore.validate(JSON.parse(await file.text()));message(`読込内容：${Object.keys(pending.materials).length}種類・履歴${pending.history.length}件。現在の在庫を置き換えるには「読み込んだ在庫に置き換える」を押してください。`);$('inventoryRestore').disabled=false;}catch(err){message(err.message);}e.target.value='';});
$('inventoryRestore').addEventListener('click',()=>{try{if(!pending)return;I.restore(pending);pending=null;$('inventoryRestore').disabled=true;render();load();message('読み込んだ在庫を保存しました。');document.dispatchEvent(new Event('inventorychange'));}catch(e){message(e.message);}});
render();load();if(I.error)message(I.error);
})();
