(function(){
 'use strict';const $=id=>document.getElementById(id),W=MakerWorkflow;
 const sample='用途：本人\n名前／SNSネーム：サンプル\n生年月日：1987-04-25\n叶えたいこと：仕事運、人間関係\n好きな色：グリーン、ブルー\nお好きな形、大きさ：ピラミッド中\nどんな未来にしたいですか：新しい仕事に自信を持って前進したい';
 const settingKey='orgonite.production.v1';let settings={available:StoneSelector.STONES.filter(s=>s.stock).map(s=>s.id),maxStones:3,materials:'レジン・銅線',verified:false};
 try{const s=JSON.parse(localStorage.getItem(settingKey)||'null');if(s)settings=s}catch{};
 let cacheText,cache;
 function context(){try{const text=$('pipelineState').value;if(text!==cacheText){cache=JSON.parse(text||'null');cacheText=text;if(cache)cache.sanmei=W.normalize(cache.sanmei.raw,cache.sanmei.conditions)}return cache}catch{return null}}
 function node(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
 function error(message){$('intakeStatus').textContent=message;}
 function saveSettings(){settings={available:[...$('inventoryList').querySelectorAll('input:checked')].map(el=>el.value),maxStones:Number($('maxStones').value),materials:$('standardMaterials').value.trim(),verified:$('inventoryVerified').checked};if(!settings.materials||!settings.available.length){settings.verified=false;$('inventoryVerified').checked=false;$('settingStatus').textContent='使用できる石と標準素材を設定してください。';return;}try{localStorage.setItem(settingKey,JSON.stringify(settings));$('settingStatus').textContent='制作設定を保存しました。次の案件でも使います。'}catch{$('settingStatus').textContent='設定を保存できませんでした。'}const c=context();if(c){c.accepted=false;MakerEditor.apply({pipelineState:JSON.stringify(c)});$('intakeStatus').textContent='制作設定が変わりました。「回答から自動提案」で提案を更新してください。';}}
 $('maxStones').value=String(settings.maxStones);$('standardMaterials').value=settings.materials;$('inventoryVerified').checked=Boolean(settings.verified);
 for(const stone of StoneSelector.STONES){const label=node('label',null,'inventory-option'),input=node('input');input.type='checkbox';input.value=stone.id;input.checked=settings.available.includes(stone.id);label.append(input,document.createTextNode(stone.name));$('inventoryList').append(label);}
 $('saveProduction').addEventListener('click',saveSettings);
 function intake(){try{const parsed=W.parse($('formAnswer').value),sets=W.recommend(parsed.customer,settings.available,settings.maxStones);const c={...parsed,sets,selected:0,accepted:false,settings:{...settings},finalShape:parsed.customer.shape.split(/[、,\n]/).length===1?parsed.customer.shape:''};MakerEditor.newCase({formAnswer:c.sourceText,pipelineState:JSON.stringify(c)});error('自動提案しました。推奨セットを確認して採用してください。');}catch(e){error(e.message)}}
 function apply(c,accepted=false){if(c.finalShape==='')return error('形・サイズの希望が複数あります。使用する形を選んでください。');const customer={...c.customer,shape:c.finalShape};const fields=W.fields(customer,c.sanmei,c.sets[c.selected],c.settings);c.accepted=accepted;MakerEditor.apply({...fields,pipelineState:JSON.stringify(c)});error(accepted?'採用しました。内容を確認してプロンプトをコピーできます。':'提案を反映しました。確認後に採用してください。');}
 function adopt(){const c=context();if(!c)return;if($('formAnswer').value.trim()!==c.sourceText)return error('回答が変更されています。自動提案を更新してください。');if(JSON.stringify(settings)!==JSON.stringify(c.settings))return error('制作設定が変更されています。自動提案を更新してください。');if(!settings.verified)return error('初回だけ「制作設定」で実際に使用できる石・素材を確認し、保存してください。');apply(c,true);}
 function refresh(){const c=context();const host=$('recommendations');host.replaceChildren();$('adoptSet').disabled=!c;$('sanmeiFacts').textContent=c?W.facts(c.sanmei):'回答取り込み後に、既存エンジンの結果を表示します。';$('reading').readOnly=Boolean(c);
  for(const id of ['material1','material2','material3','stone1','stone2','stone3'])$(id).readOnly=Boolean(c);
  if(!c){$('pipelineSummary').textContent='① 回答を取り込む → ② セットを採用 → ③ プロンプトをコピー';$('sanmeiCondition').textContent='';$('shapeChoice').hidden=true;return;}
  const unknown=!c.sanmei.conditions.timeKnown;$('sanmeiCondition').textContent=unknown?'出生時刻不明：12:00の暫定結果。節入り日は年柱・月柱が変わる可能性があります。':'出生時刻を含む既存計算結果。';
  $('pipelineSummary').textContent=`${c.customer.name}様／${c.customer.purpose==='gift'?'受取人への贈り物':'本人用'}／${c.accepted?'採用済み':'提案を確認中'}`;
  c.sets.forEach((set,index)=>{const card=node('section',null,'set-card'+(index===c.selected?' selected':''));card.append(node('h3',index===0?'おすすめセット':`代替セット ${index}`));set.stones.forEach(s=>{card.append(node('p',`${s.role}：${s.name}`),node('small',`役割：${s.keywords.slice(0,2).join('・')}／回答との対応：${s.matches.join('・')||'色・未来の語句'}\n${s.reasons.join('／')}`));});if(set.uncovered.length)card.append(node('p','対応未登録の願い：'+set.uncovered.join('・'),'notice'));if(set.unmatchedColors.length)card.append(node('p','石にない希望色：'+set.unmatchedColors.join('・')+'（作品配色として保持）','hint'));const button=node('button',index===c.selected?'現在のセット':'このセットに切替','btn');button.type='button';button.disabled=index===c.selected;button.addEventListener('click',()=>{c.selected=index;c.accepted=false;apply(c,false)});card.append(button);host.append(card);});
  const shapes=c.customer.shape.split(/[、,\n]/).map(s=>s.trim()).filter(Boolean);$('shapeChoice').hidden=shapes.length<2;$('finalShape').replaceChildren(...['',...shapes].map(s=>{const o=node('option',s||'使用する形・サイズを選択');o.value=s;return o}));$('finalShape').value=c.finalShape;
  const swap=$('stoneSwaps');swap.replaceChildren();c.sets[c.selected].stones.forEach((s,i)=>{const label=node('label',s.role,'field'),select=node('select');select.setAttribute('aria-label',s.role+'の差し替え');const currentIds=c.sets[c.selected].stones.map(s=>s.id);for(const stone of StoneSelector.STONES.filter(s=>c.settings.available.includes(s.id)&&(!currentIds.includes(s.id)||s.id===currentIds[i]))){const o=node('option',stone.name);o.value=stone.id;select.append(o)}select.value=s.id;select.addEventListener('change',()=>{const stone=StoneSelector.STONES.find(s=>s.id===select.value),score=StoneSelector.score(stone,{wishes:c.customer.wishes,colors:c.customer.colors,future:c.customer.future});c.sets[c.selected].stones[i]={id:stone.id,name:stone.name,role:i===0?'メイン':'サブ',keywords:stone.keywords,colors:stone.colors,matches:stone.wishes.filter(w=>c.customer.wishes.includes(w)),reasons:['制作者が差し替え',...score.reasons]};const set=c.sets[c.selected];set.uncovered=c.customer.wishes.filter(w=>!set.stones.some(s=>s.matches.includes(w)));set.unmatchedColors=c.customer.colors.filter(color=>!set.stones.some(s=>s.colors.includes(color)));c.accepted=false;apply(c,false)});label.append(select);swap.append(label);});
  // 石・命式は共通データから自動反映。通常の編集欄から分岐した値を作らない。
  for(const id of ['material1','material2','material3','stone1','stone2','stone3'])$(id).readOnly=true;
 }
 function guards(){const c=context();if(!c)return [];const errors=[];if(!c.accepted)errors.push({id:'adoptSet',text:'自動提案のセットを確認して採用してください。'});if($('formAnswer').value.trim()!==c.sourceText)errors.push({id:'formAnswer',text:'回答が変更されています。自動提案を更新してください。'});if(JSON.stringify(settings)!==JSON.stringify(c.settings))errors.push({id:'saveProduction',text:'現在の制作設定と案件の設定が異なります。設定を確認して自動提案を更新してください。'});return errors;}
 $('formAnswer').addEventListener('input',()=>{const c=context();if(c){c.accepted=false;MakerEditor.apply({pipelineState:JSON.stringify(c)},false)}MakerEditor.render()});
 $('finalShape').addEventListener('change',()=>{const c=context();if(c){c.finalShape=$('finalShape').value;c.accepted=false;apply(c,false)}});
 $('importAnswer').addEventListener('click',intake);$('sampleAnswer').addEventListener('click',()=>{$('formAnswer').value=sample;intake()});$('adoptSet').addEventListener('click',adopt);
 $('exportCase').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({format:'orgonite-case-v1',fields:MakerEditor.state()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='orgonite-case.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 $('importCase').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('案件JSONは2MB以下にしてください。');const data=JSON.parse(await file.text());if(data.format!=='orgonite-case-v1'||typeof data.fields!=='object')throw Error('Prompt Makerで保存した案件JSONを選んでください。');const c=JSON.parse(data.fields.pipelineState||'null');if(c){const raw=JSON.parse(JSON.stringify(c.sanmei.raw));c.sanmei=W.normalize(raw,c.sanmei.conditions);if(c.customer.birthDate!==raw.input.date)throw Error('案件の日付と計算結果が一致しません。');data.fields.pipelineState=JSON.stringify(c);}MakerEditor.newCase(data.fields);error('案件を復元しました。作品写真は再選択してください。')}catch(e){error('復元できませんでした：'+e.message)}e.target.value=''});
 window.MakerUI={refresh,guards,context,intake,adopt};refresh();MakerEditor.render();
})();
